name: Android CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'androidApp/**/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'androidApp/**/*'

env:
  # BUILD_PATH: "." default value when not using subfolders
  BUILD_PATH: "./androidApp"

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions: write-all

    steps:
    - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ${{ github.workspace }}/${{ env.BUILD_PATH }}/gradlew
      working-directory: androidApp

    
    - run: echo "Building Debug APK."
    - name: Build with Gradle
      run: ${{ github.workspace }}/${{ env.BUILD_PATH }}/gradlew build
      working-directory: androidApp
    - run: echo "Build status report=${{ job.status }}."
    - name: Run tests
      run: ${{ github.workspace }}/${{ env.BUILD_PATH }}/gradlew test
      working-directory: androidApp

  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
      with:
        fetch-depth: 0 # Fetches all history for all branches and tags
    - uses: axel-op/googlejavaformat-action@v3
      with:
        args: "--skip-sorting-imports --replace"
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Squash formatting commit into the previous commit
      run: |
        git config --global user.name "Pedro Guillermo Feijóo-García"
        git config --global user.email "pfeijoo@gatech.edu"
        git reset --soft HEAD~2
        git commit --amend --author="Pedro Guillermo Feijóo-García <pfeijoo@gatech.edu>" --no-edit
        git push origin main --force
